// This file was auto-generated by Fern from our API Definition.

package tenants

import (
	context "context"
	fmt "fmt"
	core "github.com/trycourier/courier-go/v3/core"
	users "github.com/trycourier/courier-go/v3/users"
	http "net/http"
	url "net/url"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header
}

func NewClient(opts ...core.ClientOption) *Client {
	options := core.NewClientOptions()
	for _, opt := range opts {
		opt(options)
	}
	return &Client{
		baseURL: options.BaseURL,
		caller:  core.NewCaller(options.HTTPClient),
		header:  options.ToHeader(),
	}
}

// This endpoint is used to add a user to
// multiple tenants in one call.
// A custom profile can also be supplied for each tenant.
// This profile will be merged with the user's main
// profile when sending to the user with that tenant.
//
// The user's ID. This can be any uniquely identifiable string.
func (c *Client) AddMultple(ctx context.Context, userId string, request *users.AddUserToMultipleTenantsParams) error {
	baseURL := "https://api.courier.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	endpointURL := fmt.Sprintf(baseURL+"/"+"users/%v/tenants", userId)

	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:     endpointURL,
			Method:  http.MethodPut,
			Headers: c.header,
			Request: request,
		},
	); err != nil {
		return err
	}
	return nil
}

// This endpoint is used to add a single tenant.
//
// A custom profile can also be supplied with the tenant.
// This profile will be merged with the user's main profile
// when sending to the user with that tenant.
//
// Id of the user to be added to the supplied tenant.
// Id of the tenant the user should be added to.
func (c *Client) Add(ctx context.Context, userId string, tenantId string, request *users.AddUserToSingleTenantsParams) error {
	baseURL := "https://api.courier.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	endpointURL := fmt.Sprintf(baseURL+"/"+"users/%v/tenants/%v", userId, tenantId)

	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:     endpointURL,
			Method:  http.MethodPut,
			Headers: c.header,
			Request: request,
		},
	); err != nil {
		return err
	}
	return nil
}

// Removes a user from the supplied tenant.
//
// Id of the user to be removed from the supplied tenant.
// Id of the tenant the user should be removed from.
func (c *Client) Remove(ctx context.Context, userId string, tenantId string) error {
	baseURL := "https://api.courier.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	endpointURL := fmt.Sprintf(baseURL+"/"+"users/%v/tenants/%v", userId, tenantId)

	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:     endpointURL,
			Method:  http.MethodDelete,
			Headers: c.header,
		},
	); err != nil {
		return err
	}
	return nil
}

// Returns a paginated list of user tenant associations.
//
// Id of the user to retrieve all associated tenants for.
func (c *Client) List(ctx context.Context, userId string, request *users.ListTenantsForUserParams) (*users.ListTenantsForUserResponse, error) {
	baseURL := "https://api.courier.com"
	if c.baseURL != "" {
		baseURL = c.baseURL
	}
	endpointURL := fmt.Sprintf(baseURL+"/"+"users/%v/tenants", userId)

	queryParams := make(url.Values)
	if request.Limit != nil {
		queryParams.Add("limit", fmt.Sprintf("%v", *request.Limit))
	}
	if request.StartingAfter != nil {
		queryParams.Add("starting_after", fmt.Sprintf("%v", *request.StartingAfter))
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}

	var response *users.ListTenantsForUserResponse
	if err := c.caller.Call(
		ctx,
		&core.CallParams{
			URL:      endpointURL,
			Method:   http.MethodGet,
			Headers:  c.header,
			Response: &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
