// This file was auto-generated by Fern from our API Definition.

package client

import (
	core "github.com/trycourier/courier-go/v3/core"
	option "github.com/trycourier/courier-go/v3/option"
	preferences "github.com/trycourier/courier-go/v3/users/preferences"
	tenants "github.com/trycourier/courier-go/v3/users/tenants"
	tokens "github.com/trycourier/courier-go/v3/users/tokens"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header

	Preferences *preferences.Client
	Tenants     *tenants.Client
	Tokens      *tokens.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL:     options.BaseURL,
		caller:      core.NewCaller(options.HTTPClient),
		header:      options.ToHeader(),
		Preferences: preferences.NewClient(opts...),
		Tenants:     tenants.NewClient(opts...),
		Tokens:      tokens.NewClient(opts...),
	}
}
