// Code generated by Fern. DO NOT EDIT.

package preferences

import (
	context "context"
	core "github.com/trycourier/courier-go/v3/core"
	internal "github.com/trycourier/courier-go/v3/internal"
	option "github.com/trycourier/courier-go/v3/option"
	users "github.com/trycourier/courier-go/v3/users"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.AuthorizationToken == "" {
		options.AuthorizationToken = os.Getenv("COURIER_AUTH_TOKEN")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Fetch all user preferences.
func (c *Client) List(
	ctx context.Context,
	// A unique identifier associated with the user whose preferences you wish to retrieve.
	userId string,
	request *users.UserPreferencesParams,
	opts ...option.RequestOption,
) (*users.UserPreferencesListResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		userId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Fetch user preferences for a specific subscription topic.
func (c *Client) Get(
	ctx context.Context,
	// A unique identifier associated with the user whose preferences you wish to retrieve.
	userId string,
	// A unique identifier associated with a subscription topic.
	topicId string,
	request *users.UserPreferencesTopicParams,
	opts ...option.RequestOption,
) (*users.UserPreferencesGetResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		userId,
		topicId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update or Create user preferences for a specific subscription topic.
func (c *Client) Update(
	ctx context.Context,
	// A unique identifier associated with the user whose preferences you wish to retrieve.
	userId string,
	// A unique identifier associated with a subscription topic.
	topicId string,
	request *users.UserPreferencesUpdateParams,
	opts ...option.RequestOption,
) (*users.UserPreferencesUpdateResponse, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		userId,
		topicId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
