// This file was auto-generated by Fern from our API Definition.

package option

import (
	core "github.com/trycourier/courier-go/v3/core"
)

// IdempotentRequestOption adapts the behavior of an indivdual request.
type IdempotentRequestOption = core.IdempotentRequestOption

// WithIdempotencyKey sets the idempotencyKey request header.
func WithIdempotencyKey(idempotencyKey *string) *core.IdempotencyKeyOption {
	return &core.IdempotencyKeyOption{
		IdempotencyKey: idempotencyKey,
	}
}

// WithIdempotencyExpiry sets the idempotencyExpiry request header.
func WithIdempotencyExpiry(idempotencyExpiry *int) *core.IdempotencyExpiryOption {
	return &core.IdempotencyExpiryOption{
		IdempotencyExpiry: idempotencyExpiry,
	}
}
