// Code generated by Fern. DO NOT EDIT.

package translations

import (
	context "context"
	core "github.com/trycourier/courier-go/v3/core"
	internal "github.com/trycourier/courier-go/v3/internal"
	option "github.com/trycourier/courier-go/v3/option"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.AuthorizationToken == "" {
		options.AuthorizationToken = os.Getenv("COURIER_AUTH_TOKEN")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Get translations by locale
func (c *Client) Get(
	ctx context.Context,
	// The domain you want to retrieve translations for. Only `default` is supported at the moment
	domain string,
	// The locale you want to retrieve the translations for
	locale string,
	opts ...option.RequestOption,
) (string, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		domain,
		locale,
		opts...,
	)
	if err != nil {
		return "", err
	}
	return response.Body, nil
}

// Update a translation
func (c *Client) Update(
	ctx context.Context,
	// The domain you want to retrieve translations for. Only `default` is supported at the moment
	domain string,
	// The locale you want to retrieve the translations for
	locale string,
	request string,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Update(
		ctx,
		domain,
		locale,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
