// Code generated by Fern. DO NOT EDIT.

package auditevents

import (
	context "context"
	v3 "github.com/trycourier/courier-go/v3"
	core "github.com/trycourier/courier-go/v3/core"
	internal "github.com/trycourier/courier-go/v3/internal"
	option "github.com/trycourier/courier-go/v3/option"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.AuthorizationToken == "" {
		options.AuthorizationToken = os.Getenv("COURIER_AUTH_TOKEN")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Fetch the list of audit events
func (c *Client) List(
	ctx context.Context,
	request *v3.ListAuditEventsRequest,
	opts ...option.RequestOption,
) (*v3.ListAuditEventsResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Fetch a specific audit event by ID.
func (c *Client) Get(
	ctx context.Context,
	// A unique identifier associated with the audit event you wish to retrieve
	auditEventId string,
	opts ...option.RequestOption,
) (*v3.AuditEvent, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		auditEventId,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
